[package]
name = "rift-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1", features = ["rt-multi-thread"]}
poise = "0.3.0" 
dotenv = "0.15.0"

[dependencies.serenity]
version = "0.11"
default-features = false
features = ["builder", "client", "gateway", "model", "utils", "collector"]