name: simple

on: push

jobs:
  simple:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    # Half of this code is designed to cahce the dependencys, which doesnt work only the run section at the very end anyone should care about
    name: Test `cargo check/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2

      
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal
          cargo clippy
          cargo fmt